repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml

  - repo: https://github.com/openstack/bashate
    rev: 2.1.1
    hooks:
      - id: bashate

  - repo: https://github.com/adamchainz/djade-pre-commit
    rev: 1.3.2
    hooks:
      - id: djade
        args: [--target-version, '5.1']

  - repo: https://github.com/djlint/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-reformat-django
      - id: djlint-django

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [css, javascript, json, markdown, yaml]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.22.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@9.22.0
          - globals@16.0.0

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        args: ['-c', 'pyproject.toml']

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-django==1.1.1
          - Flake8-pyproject==1.2.3

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: ./venv/bin/pylint
        language: system
        types: [python]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies: [types-all-v2]
        args: ['--config-file', 'pyproject.toml']
