# This file contains settings for local development to override the ones
# contained in `docker-compose.yaml`

services:
  web-app:
    image: nsorokopud/django_articles:web-app-dev
    build:
      context: .
      args:
        REQUIREMENTS_FILE: requirements-dev.txt
    env_file: !override
      - .env.docker
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.local
    command: ['python', 'manage.py', 'runserver', '0.0.0.0:8000']
    ports:
      - '8000:8000'
    volumes:
      - .:/app # Mount project dir to avoid image rebuilding

  celery-worker:
    image: nsorokopud/django_articles:web-app-dev
    build:
      context: .
      args:
        REQUIREMENTS_FILE: requirements-dev.txt
    env_file: !override
      - .env.docker
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.local
    volumes:
      - .:/app

  celery-beat:
    image: nsorokopud/django_articles:web-app-dev
    build:
      context: .
      args:
        REQUIREMENTS_FILE: requirements-dev.txt
    env_file: !override
      - .env.docker
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.local
    volumes:
      - .:/app

  flower:
    image: nsorokopud/django_articles:web-app-dev
    build:
      context: .
      args:
        REQUIREMENTS_FILE: requirements-dev.txt
    env_file: !override
      - .env.docker
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.local
    volumes:
      - .:/app

  nginx:
    image: nsorokopud/django_articles:nginx-dev
    build:
      context: ./nginx
      args:
        NGINX_TEMPLATE: http
    ports: !override
      - '127.0.0.1:80:80'

  db:
    ports:
      - '127.0.0.1:5432:5432'

  redis:
    ports:
      - '127.0.0.1:6379:6379'
