services:
  web-app:
    image: nsorokopud/django_articles:web-app
    build: .
    restart: 'unless-stopped'
    env_file:
      - .env
    expose:
      - 8000
    volumes:
      - media-volume:/app/media/
      - static-volume:/app/staticfiles/
      - logs-volume:/app/logs/
    depends_on:
      - db
      - redis
      - celery-worker

  db:
    image: postgres:17.0-alpine
    restart: 'unless-stopped'
    expose:
      - 5432
    environment:
      POSTGRES_DB: ${DB_NAME:?DB_NAME is required}
      POSTGRES_USER: ${DB_USER:?DB_USER is required}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD is required}
    volumes:
      - db-volume:/var/lib/postgresql/data/

  celery-worker:
    image: nsorokopud/django_articles:web-app
    build: .
    restart: 'unless-stopped'
    env_file:
      - .env
    entrypoint: celery
    command: -A config worker -l INFO
    volumes:
      - media-volume:/app/media/
      - logs-volume:/app/logs/
    depends_on:
      - redis
      - db

  celery-beat:
    image: nsorokopud/django_articles:web-app
    build: .
    restart: 'unless-stopped'
    env_file:
      - .env
    entrypoint: celery
    command: -A config beat -l INFO
    volumes:
      - logs-volume:/app/logs/
    depends_on:
      - redis
      - db

  redis:
    image: redis:7.4-alpine
    restart: 'unless-stopped'
    expose:
      - 6379

  flower:
    image: nsorokopud/django_articles:web-app
    build: .
    restart: 'unless-stopped'
    env_file:
      - .env
    environment:
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME:?DJANGO_SUPERUSER_USERNAME is required}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD:?DJANGO_SUPERUSER_PASSWORD is required}
    entrypoint: celery
    command: >
      -A config flower --url-prefix=__flower__
      --basic-auth=${DJANGO_SUPERUSER_USERNAME}:${DJANGO_SUPERUSER_PASSWORD}
    expose:
      - 5555
    depends_on:
      - web-app
      - celery-worker

  nginx:
    image: nsorokopud/django_articles:nginx-${SCHEME:?SCHEME is required}
    build:
      context: ./nginx
      args:
        SCHEME: ${SCHEME:?SCHEME is required}
    restart: 'unless-stopped'
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME:?DOMAIN_NAME is required}
      SSL_CERT_PATH: /etc/letsencrypt/live/${DOMAIN_NAME:?DOMAIN_NAME is required}/fullchain.pem
      SSL_CERT_KEY_PATH: /etc/letsencrypt/live/${DOMAIN_NAME:?DOMAIN_NAME is required}/privkey.pem
      CERTBOT_EMAIL: ${CERTBOT_EMAIL:?CERTBOT_EMAIL is required}
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web-app
      - flower
    volumes:
      - media-volume:/app-media/
      - static-volume:/static/
      - ssl-cert-volume:/etc/letsencrypt/

volumes:
  db-volume:
  logs-volume:
  media-volume:
  static-volume:
  ssl-cert-volume:
