# This file contains settings for local development to override the ones
# contained in `docker-compose.yaml`

services:
  web-app:
    build:
      context: .
      args:
        REQUIREMENTS_FILE: requirements-dev.txt
    env_file: !override
      - .env.docker
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.local
    command: ['python', 'manage.py', 'runserver', '0.0.0.0:8000']
    ports:
      - 8000:8000
      - 8001:5678 # Debugger
    volumes:
      - .:/app # Mount project dir to avoid image rebuilding

  celery-worker:
    build:
      context: .
      args:
        REQUIREMENTS_FILE: requirements-dev.txt
    env_file: !override
      - .env.docker
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.local

  celery-beat:
    build:
      context: .
      args:
        REQUIREMENTS_FILE: requirements-dev.txt
    env_file: !override
      - .env.docker
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.local

  flower:
    build:
      context: .
      args:
        REQUIREMENTS_FILE: requirements-dev.txt
    env_file: !override
      - .env.docker
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.local

  nginx:
    image: nsorokopud/django_articles:nginx-http-local
    build:
      context: ./nginx
      args:
        NGINX_TEMPLATE: http
    ports: !override
      - 80:80

  db:
    ports:
      - 5432:5432

  redis:
    ports:
      - 6379:6379
