
[tool.bandit]
exclude_dirs = ["venv", ".venv", "tests", "node_modules"]

[tool.black]
target-version = ["py312"]
line-length = 88

[tool.djlint]
profile="django"
indent = 2
max_line_length = 80
format_attribute_template_tags=true
max_blank_lines=1
ignore="H006,H031,T003"

[tool.flake8]
max-line-length = 88
extend-ignore = ["W503"]
exclude = "venv,node_modules,migrations"
per-file-ignores = """
  __init__.py: F401,F403
  config/settings/test.py: F401,F403
  */migrations/*: E501
  */tests/*: F841
"""

[tool.isort]
profile = "black"
line_length = 88
lines_after_imports = 2
known_first_party = "articles,core,notifications,tests,users"

[tool.mypy]
ignore_missing_imports = true
show_column_numbers = true
explicit_package_bases = true
exclude = ['admin.py']

[tool.pylint]
load-plugins = ["pylint_django", "pylint_per_file_ignores"]
django-settings-module="config.settings"
max-line-length = 88
disable = [
  "C0114", "C0115", "C0116", "C0207", "C0411", "C0415",
  "R0901", "R0903", "R1710", "W0201, W0221"
]
ignored-argument-names="_.*|^ignored_|^unused_|request|sender"
ignore = "venv,.venv,node_modules"
per-file-ignores = [
  "filters.py:W0613",
  "commands/:W0718",
  "migrations/:C0103,C0301",
  "services.py:R0913",
  "tasks.py:W0621",
  "tests/:R0401,R0801,R0904,R0915,W0104,W0612",
  "users/auth_backends.py:C0103",
  "settings/test.py:R0401,R0801,W0401,W0614"
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings.test"
python_files = "test_*.py"
addopts = "-v -n=auto --dist=loadfile --reuse-db --maxfail=5 --disable-warnings ."
