
[tool.bandit]
exclude_dirs = ["venv", ".venv", "tests", "node_modules"]

[tool.black]
target-version = ["py312"]
line-length = 88

[tool.djlint]
profile="django"
indent = 2
max_line_length = 80
format_attribute_template_tags=true
max_blank_lines=1
ignore="H006,H031,T003"

[tool.isort]
profile = "black"
line_length = 88
lines_after_imports = 2
known_first_party = "articles,core,notifications,tests,users"

[tool.mypy]
ignore_missing_imports = true
show_column_numbers = true
explicit_package_bases = true
exclude = ['admin.py']

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings.test"
python_files = "test_*.py"
addopts = "-v -n=auto --dist=loadfile --reuse-db --maxfail=5 --disable-warnings ."
