from ..env import env


# WebSocket producer
NOTIFICATIONS_WS_DETAILED_NOTIFICATION_COOLDOWN_SECONDS = env.int(
    "NOTIFICATIONS_WS_DETAILED_NOTIFICATION_COOLDOWN_SECONDS", default=2
)
NOTIFICATIONS_WS_DIGEST_HINT_COOLDOWN_SECONDS = env.int(
    "NOTIFICATIONS_WS_DIGEST_HINT_COOLDOWN_SECONDS", default=30
)
NOTIFICATIONS_WS_GROUP_SEND_TIMEOUT_SECONDS = env.int(
    "NOTIFICATIONS_WS_GROUP_SEND_TIMEOUT_SECONDS", default=1
)

# WebSocket consumer
NOTIFICATIONS_WS_ACCEPT_TIMEOUT_SECONDS = env.int(
    "NOTIFICATIONS_WS_ACCEPT_TIMEOUT_SECONDS", default=5
)
NOTIFICATIONS_WS_GROUP_OPERATION_TIMEOUT_SECONDS = env.int(
    "NOTIFICATIONS_WS_GROUP_OPERATION_TIMEOUT_SECONDS", default=2
)
NOTIFICATIONS_WS_SEND_JSON_TIMEOUT_SECONDS = env.int(
    "NOTIFICATIONS_WS_SEND_JSON_TIMEOUT_SECONDS", default=2
)

# Retention
NOTIFICATIONS_READ_RETENTION_DAYS = env.int(
    "NOTIFICATIONS_READ_RETENTION_DAYS", default=90
)
NOTIFICATIONS_CLEANUP_BATCH_SIZE = env.int(
    "NOTIFICATIONS_CLEANUP_BATCH_SIZE", default=5000
)
NOTIFICATIONS_CLEANUP_MAX_BATCHES = env.int(
    "NOTIFICATIONS_CLEANUP_MAX_BATCHES", default=10
)
# Should be longer than the max duration of a cleanup run to prevent concurrent cleanups
NOTIFICATIONS_CLEANUP_LOCK_TTL_SECONDS = env.int(
    "NOTIFICATIONS_CLEANUP_LOCK_TTL_SECONDS", default=5400  # 1.5 hours
)

# Unread count sync
NOTIFICATIONS_UNREAD_COUNT_SYNC_LOCK_TTL_SECONDS = env.int(
    "NOTIFICATIONS_UNREAD_COUNT_SYNC_LOCK_TTL_SECONDS", default=1800  # 30 minutes
)
NOTIFICATIONS_UNREAD_COUNT_SYNC_BATCH_SIZE = env.int(
    "NOTIFICATIONS_UNREAD_COUNT_SYNC_BATCH_SIZE", default=1000
)
