# Generated by Django 4.0.1 on 2022-02-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='users/profile_images/default_avatar.jpg', upload_to='users/profile_images/'),
        ),
    ]
