# Generated by Django 5.1.1 on 2025-05-26 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_tokencounter"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notifications_enabled", models.BooleanField(default=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["subscriber"], name="users_autho_subscri_3ddef0_idx"
                    ),
                    models.Index(
                        fields=["author"], name="users_autho_author__7de617_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("subscriber", models.F("author")), _negated=True
                        ),
                        name="prevent_self_subscription",
                    ),
                    models.UniqueConstraint(
                        fields=("subscriber", "author"), name="unique_subscription"
                    ),
                ],
            },
        ),
    ]
