# Generated by Django 5.1.1 on 2025-05-26 20:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_authorsubscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="subscribers",
        ),
        migrations.AddField(
            model_name="user",
            name="subscribed_to_authors",
            field=models.ManyToManyField(
                related_name="subscribers",
                through="users.AuthorSubscription",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
