# Generated by Django 4.0.1 on 2022-01-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArticleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("slug", models.CharField(max_length=256, unique=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
    ]
