# Generated by Django 5.1.1 on 2026-03-07 13:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"verbose_name_plural": "Articles"},
        ),
        migrations.RemoveField(
            model_name="article",
            name="is_published",
        ),
        migrations.AddField(
            model_name="article",
            name="publish_sequence",
            field=models.BigIntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="published_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                condition=models.Q(("publish_sequence__isnull", False)),
                fields=["author", "-publish_sequence", "-id"],
                name="art_author_pub_seq_id_desc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                condition=models.Q(("publish_sequence__isnull", False)),
                fields=["-publish_sequence"],
                name="article_publish_seq_desc_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.UniqueConstraint(
                condition=models.Q(("publish_sequence__isnull", False)),
                fields=("publish_sequence",),
                name="uniq_article_publish_sequence_not_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("publish_sequence__isnull", True),
                        ("published_at__isnull", True),
                    ),
                    models.Q(
                        ("publish_sequence__isnull", False),
                        ("published_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="article_publish_fields_consistent",
            ),
        ),
    ]
