# Generated by Django 5.1.1 on 2026-03-17 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_alter_article_options_remove_article_is_published_and_more"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                condition=models.Q(("status", "published")),
                fields=["author", "-published_at", "-id"],
                name="art_author_pub_at_id_desc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                condition=models.Q(("status", "published")),
                fields=["-published_at", "-id"],
                name="article_pub_at_id_desc_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("published_at__isnull", False),
                        ("status", "published"),
                    ),
                    models.Q(
                        ("published_at__isnull", True),
                        ("status__in", ["draft", "rejected"]),
                    ),
                    _connector="OR",
                ),
                name="art_status_matches_publ_fields",
            ),
        ),
    ]
