# Generated by Django 5.1.1 on 2026-03-07 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "articles",
            "0002_alter_article_options_remove_article_is_published_and_more",
        ),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE SEQUENCE IF NOT EXISTS article_publish_seq;",
            reverse_sql="DROP SEQUENCE IF EXISTS article_publish_seq;",
        ),
    ]
