# Generated by Django 5.1.1 on 2026-04-14 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_article_review_note_article_reviewed_at_and_more"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="article",
            name="art_status_matches_publ_fields",
        ),
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_review", "Pending review"),
                    ("published", "Published"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("publish_sequence__isnull", False),
                        ("published_at__isnull", False),
                        ("status", "published"),
                    ),
                    models.Q(
                        ("publish_sequence__isnull", True),
                        ("published_at__isnull", True),
                        ("status__in", ["draft", "pending_review", "rejected"]),
                    ),
                    _connector="OR",
                ),
                name="art_status_matches_publ_fields",
            ),
        ),
    ]
