# Generated by Django 5.1.1 on 2026-04-20 11:33

import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0006_remove_article_art_status_matches_publ_fields_and_more"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="preview_text",
            field=models.TextField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "draft"),
                    models.Q(
                        models.Q(("title", ""), _negated=True),
                        models.Q(("preview_text", ""), _negated=True),
                        models.Q(("content", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="art_non_draft_core_fields_not_blank",
            ),
        ),
    ]
