# Generated by Django 4.0.1 on 2022-02-06 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0006_article_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
        migrations.AddField(
            model_name='article',
            name='users_that_liked',
            field=models.ManyToManyField(related_name='users_that_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
