# Generated by Django 4.0.1 on 2022-02-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_articlecomment_users_that_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
