# Generated by Django 4.0.1 on 2022-02-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_article_created_at_alter_article_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preview_text',
            field=models.TextField(max_length=512),
        ),
    ]
