import os


# WS producer
DETAILED_NOTIFICATION_COOLDOWN_SECONDS = int(
    os.getenv("DETAILED_NOTIFICATION_COOLDOWN_SECONDS", "2")
)
DIGEST_HINT_COOLDOWN_SECONDS = int(os.getenv("DIGEST_HINT_COOLDOWN_SECONDS", "30"))
GROUP_SEND_TIMEOUT_SECONDS = int(os.getenv("GROUP_SEND_TIMEOUT_SECONDS", "1"))

# WS consumer
ACCEPT_TIMEOUT_SECONDS = int(os.getenv("ACCEPT_TIMEOUT_SECONDS", "5"))
GROUP_OPERATION_TIMEOUT_SECONDS = int(os.getenv("GROUP_OPERATION_TIMEOUT_SECONDS", "2"))
SEND_JSON_TIMEOUT_SECONDS = int(os.getenv("SEND_JSON_TIMEOUT_SECONDS", "2"))

# Retention
NOTIFICATION_READ_RETENTION_DAYS = int(
    os.getenv("NOTIFICATION_READ_RETENTION_DAYS", "90")
)
NOTIFICATION_CLEANUP_BATCH_SIZE = int(
    os.getenv("NOTIFICATION_CLEANUP_BATCH_SIZE", "5000")
)
NOTIFICATION_CLEANUP_MAX_BATCHES = int(
    os.getenv("NOTIFICATION_CLEANUP_MAX_BATCHES", "10")
)
# Should be longer than the max duration of a cleanup run to prevent concurrent cleanups
NOTIFICATIONS_CLEANUP_LOCK_TTL_SECONDS = int(
    os.getenv("NOTIFICATIONS_CLEANUP_LOCK_TTL_SECONDS", "5400")  # 1.5h
)

# Unread count sync
NOTIFICATIONS_UNREAD_COUNT_SYNC_LOCK_TTL_SECONDS = int(
    os.getenv("NOTIFICATIONS_UNREAD_COUNT_SYNC_LOCK_TTL_SECONDS", "1800")  # 30 min
)
NOTIFICATIONS_UNREAD_COUNT_SYNC_BATCH_SIZE = int(
    os.getenv("NOTIFICATIONS_UNREAD_COUNT_SYNC_BATCH_SIZE", "1000")
)
