from .env import env


# WS producer
DETAILED_NOTIFICATION_COOLDOWN_SECONDS = env.int(
    "DETAILED_NOTIFICATION_COOLDOWN_SECONDS", default=2
)
DIGEST_HINT_COOLDOWN_SECONDS = env.int("DIGEST_HINT_COOLDOWN_SECONDS", default=30)
GROUP_SEND_TIMEOUT_SECONDS = env.int("GROUP_SEND_TIMEOUT_SECONDS", default=1)

# WS consumer
ACCEPT_TIMEOUT_SECONDS = env.int("ACCEPT_TIMEOUT_SECONDS", default=5)
GROUP_OPERATION_TIMEOUT_SECONDS = env.int("GROUP_OPERATION_TIMEOUT_SECONDS", default=2)
SEND_JSON_TIMEOUT_SECONDS = env.int("SEND_JSON_TIMEOUT_SECONDS", default=2)

# Retention
NOTIFICATION_READ_RETENTION_DAYS = env.int(
    "NOTIFICATION_READ_RETENTION_DAYS", default=90
)
NOTIFICATION_CLEANUP_BATCH_SIZE = env.int(
    "NOTIFICATION_CLEANUP_BATCH_SIZE", default=5000
)
NOTIFICATION_CLEANUP_MAX_BATCHES = env.int(
    "NOTIFICATION_CLEANUP_MAX_BATCHES", default=10
)
# Should be longer than the max duration of a cleanup run to prevent concurrent cleanups
NOTIFICATIONS_CLEANUP_LOCK_TTL_SECONDS = env.int(
    "NOTIFICATIONS_CLEANUP_LOCK_TTL_SECONDS", default=5400  # 1.5h
)

# Unread count sync
NOTIFICATIONS_UNREAD_COUNT_SYNC_LOCK_TTL_SECONDS = env.int(
    "NOTIFICATIONS_UNREAD_COUNT_SYNC_LOCK_TTL_SECONDS", default=1800  # 30 min
)
NOTIFICATIONS_UNREAD_COUNT_SYNC_BATCH_SIZE = env.int(
    "NOTIFICATIONS_UNREAD_COUNT_SYNC_BATCH_SIZE", default=1000
)
