name: Continuous Integration

on:
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  run_code_quality_tools:
    uses: ./.github/workflows/run-code-quality-tools.yaml

  run_tests:
    uses: ./.github/workflows/run-tests.yaml
