name: Continuous Integration

on:
  push:
    branches: ['dev']
  pull_request:
    branches: ['master']

jobs:
  run_code_quality_tools:
    uses: nsorokopud/django_articles/.github/workflows/run-code-quality-tools.yaml@dev
    secrets: inherit
  run_tests:
    uses: nsorokopud/django_articles/.github/workflows/run-tests.yaml@dev
    secrets: inherit
