name: Master CI/CD

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  run_formatters_and_linters:
    uses: nsorokopud/django_articles/.github/workflows/run-code-quality-tools.yaml@dev
    secrets: inherit

  test:
    uses: nsorokopud/django_articles/.github/workflows/run-tests.yaml@dev
    secrets: inherit

  build_images:
    runs-on: ubuntu-latest
    name: Build Docker Images
    needs: [run_formatters_and_linters, test]
    env:
      SCHEME: ${{ secrets.SCHEME }}
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Images
        run: docker compose build
      - name: Push Images
        run: |
          docker push ${{ secrets.WEB_IMAGE }}
          docker push ${{ secrets.NGINX_IMAGE }}

  deploy:
    runs-on: ubuntu-latest
    name: Continuous Deployment
    needs: [build_images]
    steps:
      - uses: actions/checkout@v4
      - name: Send docker-compose File
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} scp \
          -o StrictHostKeyChecking=no docker-compose.yaml \
          user@161.97.156.253:/home/user;
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S \
            mv /home/user/docker-compose.yaml /projects/django_articles;
            cd /projects/django_articles;
            docker compose down;
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} \
            -p ${{ secrets.DOCKERHUB_TOKEN }};
            docker pull ${{ secrets.WEB_IMAGE }};
            docker pull ${{ secrets.NGINX_IMAGE }};
            docker compose up -d;
            docker system prune -a --volumes -f;
