name: Run Tests

on:
  workflow_call:

env:
  DJANGO_SETTINGS_MODULE: config.settings.test
  DB_NAME: django_articles
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_HOST: localhost
  TEST_REDIS_URL: redis://localhost:6379/15

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests

    services:
      postgres:
        image: postgres:17.10-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: django_articles
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7.4-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.2
          cache: 'pip'

      - name: Install Python Dependencies
        run: pip install -r requirements-dev.txt

      - name: Run Django Checks
        run: python manage.py check

      - name: Check Migrations
        run: python manage.py makemigrations --check --dry-run

      - name: Run Migrations
        run: python manage.py migrate --noinput

      - name: Run Tests
        run: pytest -n=1 .
