# Generated by Django 5.1.1 on 2026-03-09 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0002_alter_notification_options_remove_notification_link_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                condition=models.Q(("read_at__isnull", False)),
                fields=["read_at", "id"],
                name="notif_read_read_at_id_idx",
            ),
        ),
    ]
