# Generated by Django 5.1.1 on 2026-03-11 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notification_notif_read_read_at_id_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="notification",
            name="notif_read_read_at_id_idx",
        ),
        migrations.AddField(
            model_name="notification",
            name="aggregate_key",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                condition=models.Q(
                    models.Q(("aggregate_key", ""), _negated=True),
                    ("read_at__isnull", True),
                    ("notification_type", "new_comment"),
                ),
                fields=["recipient", "aggregate_key", "-id"],
                name="notif_unread_aggr_lookup_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("aggregate_key", ""), _negated=True),
                    ("read_at__isnull", True),
                    ("notification_type", "new_comment"),
                ),
                fields=("recipient", "aggregate_key"),
                name="uniq_rec_unread_comm_notif_agg",
            ),
        ),
    ]
